### ISSUE TITLE
Error sending email on crash

### ISSUE THREAD

**Issue by tranquochuy** [sdolard/node-crashreporter#4]
I tried to setup email on crash report and got this:

/Users/huytran/training/bryony/crash-report/node_modules/nodemailer/lib/nodemailer.js:241
    this.mailcomposer.setMessageOption(mailOptions);
                      ^

TypeError: this.mailcomposer.setMessageOption is not a function
    at Nodemailer.setGeneralOptions (/Users/huytran/training/bryony/crash-report/node_modules/nodemailer/lib/nodemailer.js:241:23)
    at Nodemailer.generateMailObject (/Users/huytran/training/bryony/crash-report/node_modules/nodemailer/lib/nodemailer.js:196:10)
    at Nodemailer.sendMail (/Users/huytran/training/bryony/crash-report/node_modules/nodemailer/lib/nodemailer.js:184:10)
    at /Users/huytran/training/bryony/crash-report/node_modules/nodemailer/lib/nodemailer.js:69:20
    at Nodemailer.validateSettings (/Users/huytran/training/bryony/crash-report/node_modules/nodemailer/lib/nodemailer.js:173:5)
    at sendMail (/Users/huytran/training/bryony/crash-report/node_modules/nodemailer/lib/nodemailer.js:63:12)
    at Transport.transport.sendMail (/Users/huytran/trainiHuys-MacBook-Pro-2:crash-report

I fixed it by change the version of node-mailer from 0.3.x to 0.5.x
You can use my forked version to avoid this https://github.com/tranquochuy/node-crashreporter/tarball/master

**Comment by sdolard** [comment]
Fixed in 55cd0ad.
